import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header/header";
import Footer from "@/components/shared/footer/footer";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
  title: {
    template: "%s | Daftar",
    default: "Daftar - دفتر",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/logo/favicon.svg",
  },
};

const themeInitializer = `
(function () {
  try {
    const savedTheme = localStorage.getItem('theme');
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    const theme = savedTheme || (prefersDark ? 'dark' : 'light');
    document.documentElement.setAttribute('data-theme', theme);
  } catch(e) {}
})();
`;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitializer }} />
      </head>
      <body className={`bg-[var(--background)]`}>
        <AuthProvider>
          <Header />
          <Toaster />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
